#!/bin/bash
set -e 
set -o pipefail

git pull
docker-compose up -d --build
echo "Деплой закончен"
echo "Добавляем деплой в Rollbar"
JSON_DATA=$(jq --null-input --arg revision "$(git rev-parse --short HEAD)" '{"environment": "production", "revision": $revision, "rollbar_name": "Maksim_devman", "local_username": "Maksim"}')
curl -H "X-Rollbar-Access-Token: ${TOKEN_ROLLBAR}" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "${JSON_DATA}"
