#!/bin/bash
set -e 
set -o pipefail

git pull
. ./venv/bin/activate
pip install -r requirements.txt
python manage.py migrate --noinput
echo "Собрали бэкенд"
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
echo "Собрали фронтенд"
python manage.py collectstatic --noinput
systemctl daemon-reload
systemctl stop star_burger.service
systemctl start star_burger.service
echo "Деплой закончен"
echo "Добавляем деплой в Rollbar"
JSON_DATA=$(jq --null-input --arg revision "$(git rev-parse --short HEAD)" '{"environment": "production", "revision": $revision, "rollbar_name": "Maksim_devman", "local_username": "Maksim"}')
curl -H "X-Rollbar-Access-Token: ${TOKEN_ROLLBAR}" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "${JSON_DATA}"
