# Generated by Django 3.2.15 on 2023-02-27 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_auto_20230217_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='Адрес места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='requested_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время запроса координат'),
        ),
    ]
