# Generated by Django 3.2.15 on 2023-01-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230130_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='foodcartapp.order', verbose_name='Заказы'),
        ),
    ]
