# Generated by Django 3.2.15 on 2023-01-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_product_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_quantity', to='foodcartapp.product', verbose_name='Продукт')),
            ],
        ),
    ]
