# Generated by Django 3.2.15 on 2023-01-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_productquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='foodcartapp.order', verbose_name='Заказ')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
