# Generated by Django 3.2.15 on 2023-01-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230131_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элементы заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
    ]
