# Generated by Django 3.2.15 on 2023-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Адрес доставки'),
        ),
    ]
