# Generated by Django 3.2.15 on 2023-02-06 11:40

from django.db import migrations


def copy_price_to_order_items(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')
    orders_items = OrderItem.objects.all().iterator()
    for order_items in orders_items:
        try:
            price = Product.objects.get(id=order_items.product.id).price
        except AttributeError:
            continue
        order_items.price = price
        order_items.save()




class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_order_items),
    ]
