# Generated by Django 3.2.15 on 2023-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('необработанный', 'Необработанный'), ('готовится', 'Готовится'), ('у курьера', 'У курьера'), ('выполнен', 'Выполнен')], db_index=True, default='необработанный', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
