# Generated by Django 3.2.15 on 2023-02-15 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20230215_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Время создания'),
        ),
    ]
