# Generated by Django 3.2.15 on 2023-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('Сразу, электронно', 'Сразу, электронно'), ('Наличными', 'Наличными')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
