# Generated by Django 3.2.15 on 2023-03-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0075_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Адрес доставки'),
        ),
    ]
